config/routes.rb
Socialkart::Application.routes.draw do

  root :to => 'home#index'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :items, only: [:create, :destroy, :new] do 
    member { post :vote }
  end

  resources :boards, only: [:index, :show, :destroy] do
    collection { post :authorized_uids }
  end

end

app/models/authorized_uid.rb
class AuthorizedUid < ActiveRecord::Base
  attr_accessible :uid
  has_and_belongs_to_many :boards
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  slug       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Board < ActiveRecord::Base
  attr_accessible :name, :slug

  belongs_to :user 
  has_many :items
  has_and_belongs_to_many :authorized_uids
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id          :integer          not null, primary key
#  name        :string(255)      not null
#  price       :string(255)      not null
#  image_url   :string(255)
#  product_url :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  board_id    :integer
#  user_id     :integer
#

class Item < ActiveRecord::Base
  attr_accessible :image_url, :name, :price, :product_url, :votes, :board_id, :new_board
  belongs_to :board
  belongs_to :user

  has_reputation :votes, source: :user, aggregated_by: :sum

  def self.upvoters(item, board_users)
    debugger
    upvoters = []
    board_users.each do |user|  
      v = user.voted_for(item) 
      if v == 1 
        upvoters.append(user) 
      end 
    end
    return upvoters
  end


  def self.downvoters(item, board_users)
    debugger
    downvoters = []
    board_users.each do |user|  
      v = user.voted_for(item) 
      if v == -1 
        downvoters.append(user) 
      end 
    end
    return downvoters
  end


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :integer          not null, primary key
#  provider         :string(255)
#  uid              :string(255)
#  name             :string(255)
#  oauth_token      :string(255)
#  oauth_expires_at :datetime
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :oauth_expires_at, :oauth_token, :provider, :uid
  has_many :boards, :dependent => :destroy
  has_many :items, :dependent => :destroy

  has_many :evaluations, class_name: "ReputationSystem::Evaluation", as: :source

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def voted_for(item)
    #debugger
    eval = evaluations.where(target_type: item.class, target_id: item.id).present?
    if eval
      e = evaluations.where(target_type: item.class, target_id: item.id).first
      return e.value
    else
      return 0
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def signed_in_user
    if current_user.nil?
      session[:return_to] = request.fullpath
      redirect_to root_path, notice: "Please sign in"
    end
  end

  #private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_filter :signed_in_user
  before_filter :authorized_user, only: [:show]
  before_filter :owns_board, only: [:destroy]
  
  def show
    debugger
    @board = Board.find(params[:id])
    @items = @board.items
    @authorized_uids = @board.authorized_uids.select('uid').pluck(:uid)
    @board_users = []
    @board_users.append(@board.user)
    @authorized_uids.each do |uid|
      user = User.find_by_uid(uid)
      if user
        @board_users.append(user)
      end
    end
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
  end

  def index
    #debugger
    @boards = current_user.boards

    @uid = current_user.uid
    @authorized = AuthorizedUid.find_by_uid(@uid)
    if !@authorized.nil? 
      @invited_boards =  @authorized.boards
      @invited_boards.each do | ib|
        @boards.append(ib)
      end
    end

    if @boards.count == 0 && @authorized.nil?
      flash[:notice] = "Please use the bookmarklet on Flipkart to get started."
    end
  end

  def authorized_uids
    #debugger
    @board = Board.find(params[:board])
    @uids = params[:authorized_uids]
    
    @uids.each do |uid|
      @board.authorized_uids.create uid: uid 
    end

    respond_to do |format|
      format.json { head :ok }
    end
  end

  def authorized_user
    debugger
    @board = Board.find(params[:id])
    logger.info "Board id #{@board.id}"
    logger.info "current_user.uid #{current_user.uid}"
    if current_user != @board.user
      @authorized_uids = @board.authorized_uids.select("uid").pluck(:uid)
      
      unless @authorized_uids.include? current_user.uid
        logger.info "authorized_uids = #{@authorized_uids}"
        flash[:error] = "Access Denied"
        redirect_to root_path
      end
    end
  end

  def owns_board
    @board = Board.find(params[:id])
    unless @board.user == current_user
      redirect_to root_path, notice: "What are you trying to do?"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
  if current_user
    redirect_to boards_path
  end
end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :signed_in_user

  def new 
    #debugger
    
    if params[:u]
      @item = current_user.items.new
      @item.product_url = params[:u]
      @item.name = params[:t]
      @item.price = params[:s]
      @item.image_url = params[:z]

      @boards = current_user.boards
    else
      redirect_to root_url, notice: "Please use the bookmarklet"
    end
  end

  def create 
    #debugger
    if params
      if params[:item][:new_board] != ""
        @board = current_user.boards.new
        @board.name = params[:item][:new_board]
        @board.save
      else
        @board = Board.find(params[:item][:board_id])
        unless @board.user == current_user
          redirect_to root_path, error: "That board is none of your business."
        end
      end
      @item = current_user.items.new
      @item.name = params[:item][:name]
      @item.product_url = params[:item][:product_url]
      @item.image_url = params[:item][:image_url]
      @item.price = params[:item][:price]
      @item.board = @board
      @item.save
      redirect_to board_path(id: @board.id)
    end
  end

  def vote
    @value = params[:type] == "up" ? 1 : -1
    @item = Item.find(params[:id])
    @item.add_or_update_evaluation(:votes, @value, current_user)

    @board = @item.board
    @authorized_uids = @board.authorized_uids.select("uid").pluck(:uid)
    @board_users = []
    @board_users.append(@board.user)
    @authorized_uids.each do |uid|
      user = User.find_by_uid(uid)
      if user
        @board_users.append(user)
      end
    end
    respond_to do |format|
      format.html { redirect_to :back, notice: "Thanks for voting!" }
      format.js 
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

# Returns the full title on a per-page basis.
def full_title(page_title)
  base_title = "Socialkart"
  #logger.debug "page_title: #{page_title}"
  if page_title.empty?
    base_title
  else
    "#{page_title} - #{base_title}"
  end
end

def flash_class(level)
  case level
  when :notice then "alert alert-info"
  when :success then "alert alert-success"
  when :error then "alert alert-error"
  when :alert then "alert alert-error"
  end
end 

end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/boards/destroy.html.erb
<h1>Boards#destroy</h1>
<p>Find me in app/views/boards/destroy.html.erb</p>

app/views/boards/index.html.erb
<div id="boardsContainer">
  <% @boards.each do |board|  %>
  <div class="board" data-link="<%= board_path(id: board.id) %>"> 
    <%= image_tag board.items.first.image_url, class: "board_image" %>
    <span class="boardName">
      <%= board.name %>
    </span>
  </div>
  <% end %>
</div>

app/views/boards/show.html.erb
<span id="boardHeader">
  <%= @board.name %>


<%= render 'layouts/fb_invite' %>
</span>

<div id="board">
<% @items.each do |item|  %>
   
  <% @vote = current_user.voted_for(item) %>

  <div class="item">
    
    <div class="vote">
      <% if @vote == 1  %>
        <%= link_to image_tag("arrow-up-on.png"), vote_item_path(item, type: "up"), { method: "post", class: "vote-up-on", 
                                                                                       remote: true, id: "vote-up-#{item.id}"} %>
      <% else %>
        <%= link_to image_tag("arrow-up-off.png"), vote_item_path(item, type: "up"), { method: "post", class: "vote-up-off", 
                                                                                       remote: true, id: "vote-up-#{item.id}"} %>
      <% end %>

      <%= render 'items/vote_count', item: item %>

      <% if @vote == -1 %>
        <%= link_to image_tag("arrow-down-on.png"), vote_item_path(item, type: "down"), {method: "post", class: "vote-down-on", 
                                                                                        remote: true, id: "vote-down-#{item.id}"} %>

      <% else %>
        <%= link_to image_tag("arrow-down-off.png"), vote_item_path(item, type: "down"), {method: "post", class: "vote-down-off", 
                                                                                          remote: true, id: "vote-down-#{item.id}"} %>
      <% end %>
    </div>

    <%= image_tag item.image_url, class: "itemImage" %>
    <span class="itemName">
      <%= link_to item.name, item.product_url %>
    </span>

    <div id="voters-<%= item.id %>">
      <%= render 'items/voters', item: item, board_users: @board_users   %>
    </div>

  </div>

<% end %>
</div>

app/views/home/index.html.erb
<div class="center hero-unit">
 <h1>Welcome to SocialKart</h1>

 
  <h2>
    SocialKart lets you do quick comparisons of <a href="www.flipkart.com">Flipkart</a> products, with the help of your Facebook friends. 

    Drag the <a class="btn" href="javascript:var d=document,s=d.getElementById('fk-mprod-our-id').innerHTML.replace(/(\D*)/g,''),f= 'http://appdreamers.r12.railsrumble.com/items/new',x=d.getElementsByClassName('small_image')[0],l=d.location,e=encodeURIComponent,p='?v=1&u='+e(l.href)%20+'&t='+e(d.getElementsByTagName('h1')[0].title)%20+'&s='+e(s)+'&z='+e(x.src),u=f+p;window.open(u);">
    Socialkart</a> to your bookmarks bar. You will need to sign up before continuing. 

  </h2>

  <%= link_to "Sign up with Facebook", "/auth/facebook", {class: "btn btn-large btn-primary"} %>
</div>

app/views/items/_vote_count.html.erb
<%= content_tag :span, item.reputation_for(:votes).to_i, class: "vote-count", id: "item-vote-#{item.id}" %>

app/views/items/_voters.html.erb
<% @upvoters = Item.upvoters(item, board_users) %>
<% if @upvoters.count != 0 %>
  <div class="upvoters">
    <%= image_tag("arrow-up-on.png") %>
    <% @upvoters.each do |u| %>
      <%= content_tag :span, u.name, class: ".voters" %>
    <% end %>
  </div>
 <% end %>


<% @downvoters = Item.downvoters(item, board_users) %>
<% if @downvoters.count != 0 %>
  <div class="downvoters">
    <%= image_tag("arrow-down-on.png") %>
    <% @downvoters.each do |u| %>
      <%= content_tag :span, u.name, class: ".voters" %>
    <% end %>
  </div>
<% end %>

app/views/items/new.html.erb
<%= simple_form_for(@item, :html => {:class => 'form-horizontal'}, :defaults => { :label => false} ) do |f| %>
  <%= image_tag @item.image_url %>
  <%= f.input :name %>
  <%= f.input :price %>
  <%= f.input :product_url %>
  <%= f.input :image_url  %>
  
  <div class="boardlist">
    <%= f.association :board %>
    <%= link_to "Or Create a New Board", "#", :id => "newBoardButton" %>
  </div>

  <div class ="newBoard">
    <input type="text" id="board_id" name="item[new_board]" />
    <%= link_to "Or Choose an Existing Board", "#", :id => "existingBoardButton" %>
  </div>

  <%= f.button :submit %>
<% end %>

app/views/items/vote.js.erb
$('#item-vote-<%= @item.id %>').html('<%= @item.reputation_for(:votes).to_i %>');
<% if @value == 1  %>
    $('#vote-up-<%= @item.id %>').find('img').attr('src', '/assets/arrow-up-on.png');
    $('#vote-down-<%= @item.id %>').find('img').attr('src', '/assets/arrow-down-off.png');
<% else %>
    $('#vote-up-<%= @item.id %>').find('img').attr('src', '/assets/arrow-up-off.png');
    $('#vote-down-<%= @item.id %>').find('img').attr('src', '/assets/arrow-down-on.png');
<% end %>
$("#voters-<%= @item.id %>").html("")

$("#voters-<%= @item.id %>").html("<%= j render 'items/voters', item: @item, board_users: @board_users %>")

app/views/layouts/_fb_invite.html.erb
<p>
  <%= button_tag 'Invite your facebook friends', :id => 'invite_fb_friends', class: 'btn' %>
</p>

<div id="fb-root"></div>

<script src="http://connect.facebook.net/en_US/all.js"></script> 
<script type="text/javascript">
  $(function(){
    $('#invite_fb_friends').click(function() {
      FB.init({ 
        appId : '139850259434486', 
        status : true, 
        cookie : false
      });

      FB.ui({method: 'apprequests', 
             message: '<%= current_user.name %> wants your help in making a decision',
        }, 
        function (result) {
          $.post('/boards/authorized_uids', {authorized_uids: result.to, 
                                            board: <%= @board.id %>});
          // var to = res.to;
          //console.log result.to;
        } 
      ); 
    });
    });
</script>

app/views/layouts/_flash_messages.html.erb
<!-- Taken from http://stackoverflow.com/questions/8705590/custom-classes-and-formatting-on-flash-messages-for-twitter-bootstrap-defaults -->
<div id="flash_msg_container">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><a href="http://rohitmishra.me/blog">Blog</a></li>
      <li><%= link_to "Help", "#"  %></li>
      <li><%= link_to "Privacy", "#"  %></li>
      <li><%= link_to "Terms", "#"  %></li>
    </ul>
  </nav>
  <small>
    Socialkart - Built for Rails Rumble 2012
  </small>
</footer>
<script type="text/javascript">
   var rumbleBannerBackgroundColor, rumbleBannerTextColor, rumbleBannerLinkColor, rumbleBannerPlacement;
   rumbleBannerBackgroundColor = "#161616";
   rumbleBannerTextColor = "#b0b0b0";
   rumbleBannerLinkColor = "#ffffff";
   rumbleBannerPlacement = "bottom";
 </script>
<script src="http://s0.railsrumble.com/banner.js" type="text/javascript"></script>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "SocialKart", root_path, id: "logo", class: "brand"  %>
      <nav>
        <ul class="nav pull-right">
          <li><a class="btn" href="javascript:var d=document,s=d.getElementById('fk-mprod-our-id').innerHTML.replace(/(\D*)/g,''),f= 'http://appdreamers.r12.railsrumble.com/items/new',x=d.getElementsByClassName('small_image')[0],l=d.location,e=encodeURIComponent,p='?v=1&u='+e(l.href)%20+'&t='+e(d.getElementsByTagName('h1')[0].title)%20+'&s='+e(s)+'&z='+e(x.src),u=f+p;window.open(u);">
            Bookmarklet</a></li>
          <% if current_user %>
            <li><%= link_to current_user.name, root_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <b class="caret"></b>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Signout", signout_path, tabindex: "-1" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign up with Facebook", "/auth/facebook" %>
        <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">
      Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">
      install Google Chrome Frame</a> to experience this site.</p><![endif]-->
    <%= render 'layouts/header' %>
    <div id="main" role="main">
      <div class="container">
        <div class="row">
          <div class="span12">
            <%= render 'layouts/flash_messages' %>
            <%= yield %>
          </div>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
      </div>  <!-- end of row -->
    </div> <!-- end of container -->
  </div> <!-- end of main -->

  </body>
</html>

app/views/layouts/navbar.html.erb
<div id="user_nav">
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
  <% end %>
</div>